"""phase3 peer context

Adds the run-scoped analytics tables analysis_run, peer_group and
work_context (BLUEPRINT.md §4). It only creates tables: no existing table
is altered or dropped. work_context.house is indexed with run_id because
it is a display filter only, never a peer-grouping key.

Revision ID: 29e1f0ab9481
Revises: 911e666c3a2e
Create Date: 2026-09-24 17:16:33.855146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '29e1f0ab9481'
down_revision: Union[str, None] = '911e666c3a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=40), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peer_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=3), nullable=False),
    sa.Column('group_key', sa.String(length=200), nullable=False),
    sa.Column('n_works', sa.Integer(), nullable=False),
    sa.Column('n_usable', sa.Integer(), nullable=False),
    sa.Column('n_mps', sa.Integer(), nullable=False),
    sa.Column('top_mp_share', sa.Float(), nullable=True),
    sa.Column('n_ls', sa.Integer(), nullable=False),
    sa.Column('n_rs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'level', 'group_key', name='uq_peer_group_run_level_key')
    )
    op.create_table('work_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('work_key', sa.String(length=50), nullable=False),
    sa.Column('house', sa.String(length=2), nullable=False),
    sa.Column('amount_used', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('amount_basis', sa.String(length=10), nullable=True),
    sa.Column('sanction_fy', sa.String(length=7), nullable=True),
    sa.Column('level', sa.String(length=3), nullable=True),
    sa.Column('group_key', sa.String(length=200), nullable=True),
    sa.Column('n_usable_excl_self', sa.Integer(), nullable=True),
    sa.Column('distinct_other_mps', sa.Integer(), nullable=True),
    sa.Column('max_mp_share', sa.Float(), nullable=True),
    sa.Column('peer_median', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('peer_q25', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('peer_q75', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('peer_iqr', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('peer_mad', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('l1_n_usable_excl_self', sa.Integer(), nullable=True),
    sa.Column('l1_distinct_other_mps', sa.Integer(), nullable=True),
    sa.Column('l1_distinct_mps_in_peers', sa.Integer(), nullable=True),
    sa.Column('l1_distinct_mps_in_group', sa.Integer(), nullable=True),
    sa.Column('ref_group_key', sa.String(length=200), nullable=True),
    sa.Column('ref_n_usable_excl_self', sa.Integer(), nullable=True),
    sa.Column('ref_distinct_other_mps', sa.Integer(), nullable=True),
    sa.Column('ref_max_mp_share', sa.Float(), nullable=True),
    sa.Column('ref_median', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('ref_iqr', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('ref_mad', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_run.id'], ),
    sa.ForeignKeyConstraint(['work_key'], ['work.work_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'work_key', name='uq_work_context_run_work')
    )
    op.create_index('ix_work_context_run_house', 'work_context', ['run_id', 'house'], unique=False)
    op.create_index('ix_work_context_run_level', 'work_context', ['run_id', 'level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_context_run_level', table_name='work_context')
    op.drop_index('ix_work_context_run_house', table_name='work_context')
    op.drop_table('work_context')
    op.drop_table('peer_group')
    op.drop_table('analysis_run')
    # ### end Alembic commands ###
