"""phase2 normalized core schema and entity resolution

Revision ID: 911e666c3a2e
Revises: 9498471f3449
Create Date: 2026-09-24 08:45:04.133858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '911e666c3a2e'
down_revision: Union[str, None] = '9498471f3449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calamity_consent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('house', sa.String(length=2), nullable=False),
    sa.Column('calamity_name', sa.String(length=200), nullable=True),
    sa.Column('tenure_label_raw', sa.String(length=50), nullable=True),
    sa.Column('mp_raw_name', sa.String(length=200), nullable=True),
    sa.Column('consent_date', sa.Date(), nullable=True),
    sa.Column('sno', sa.Integer(), nullable=True),
    sa.Column('consented_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('calamity_type', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('implementing_agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ia_name', sa.String(length=300), nullable=False),
    sa.Column('agency_type', sa.String(length=30), nullable=False),
    sa.Column('first_seen_snapshot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_seen_snapshot_id'], ['source_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ia_name')
    )
    op.create_table('macro_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=True),
    sa.Column('fiscal_year', sa.String(length=20), nullable=True),
    sa.Column('measure', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('source_document', sa.String(length=200), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payee',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('payee_type', sa.String(length=30), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('first_seen_snapshot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_seen_snapshot_id'], ['source_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prior_cycle_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('house', sa.String(length=2), nullable=False),
    sa.Column('mp_raw_name', sa.String(length=200), nullable=True),
    sa.Column('work_description', sa.Text(), nullable=True),
    sa.Column('category_raw', sa.String(length=100), nullable=True),
    sa.Column('state_name', sa.String(length=100), nullable=True),
    sa.Column('constituency_name', sa.String(length=200), nullable=True),
    sa.Column('ida_name', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('ward', sa.String(length=200), nullable=True),
    sa.Column('block', sa.String(length=200), nullable=True),
    sa.Column('village', sa.String(length=200), nullable=True),
    sa.Column('recommended_date', sa.Date(), nullable=True),
    sa.Column('allocation_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('ida_approval_status', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payee_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payee_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('source_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payee_id'], ['payee.id'], ),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payee_id', 'name', name='uq_payee_alias_payee_name')
    )
    op.create_table('allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenure_id', sa.Integer(), nullable=False),
    sa.Column('source_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshot.id'], ),
    sa.ForeignKeyConstraint(['tenure_id'], ['tenure.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenure_id', 'source_snapshot_id', name='uq_allocation_tenure_snapshot')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('work_key', sa.String(length=50), nullable=False),
    sa.Column('payee_id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('occurrence_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['implementing_agency.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['payee.id'], ),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshot.id'], ),
    sa.ForeignKeyConstraint(['work_key'], ['work.work_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_snapshot_id', 'work_key', 'payee_id', 'payment_date', 'amount', 'occurrence_no', name='uq_payment_identity')
    )
    op.create_table('work_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_key', sa.String(length=50), nullable=False),
    sa.Column('source_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=20), nullable=False),
    sa.Column('recommended_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('recommended_date', sa.Date(), nullable=True),
    sa.Column('sanction_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('sanction_date', sa.Date(), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('raw_stage', sa.Text(), nullable=True),
    sa.Column('raw_flag', sa.String(length=10), nullable=True),
    sa.Column('raw_file_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshot.id'], ),
    sa.ForeignKeyConstraint(['work_key'], ['work.work_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_key', 'source_snapshot_id', name='uq_work_state_work_snapshot')
    )
    op.add_column('work', sa.Column('description_normalized', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'description_normalized')
    op.drop_table('work_state')
    op.drop_table('payment')
    op.drop_table('allocation')
    op.drop_table('payee_alias')
    op.drop_table('prior_cycle_work')
    op.drop_table('payee')
    op.drop_table('macro_reference')
    op.drop_table('implementing_agency')
    op.drop_table('calamity_consent')
    # ### end Alembic commands ###
