"""phase1 ingest and reference schema

Revision ID: 9498471f3449
Revises: 0001
Create Date: 2026-09-23 20:26:06.200433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9498471f3449'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('geo_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('licence', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.CheckConstraint("level IN ('national', 'state', 'district', 'constituency')", name='ck_geo_area_level'),
    sa.ForeignKeyConstraint(['parent_id'], ['geo_area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level', 'key', name='uq_geo_area_level_key')
    )
    op.create_table('source_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('portal_address', sa.String(length=500), nullable=True),
    sa.Column('retrieval_method', sa.String(length=200), nullable=True),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('imported_by', sa.String(length=100), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('portal_state_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('constituency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('house', sa.String(length=2), nullable=False),
    sa.Column('source_snapshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshot.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'state_id', name='uq_constituency_name_state')
    )
    op.create_table('district_authority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ida_name', sa.String(length=300), nullable=False),
    sa.Column('district_key', sa.String(length=200), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_snapshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_seen_snapshot_id'], ['source_snapshot.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ida_name')
    )
    op.create_table('geo_name_crosswalk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('geo_area_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['geo_area_id'], ['geo_area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_name', 'level', name='uq_geo_crosswalk_name_level')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('house_raw_code', sa.String(length=1), nullable=True),
    sa.Column('source_snapshot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshot.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('delimiter', sa.String(length=1), nullable=False),
    sa.Column('footer_total', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_snapshot_id', 'filename', name='uq_raw_file_snapshot_filename')
    )
    op.create_table('state_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_id', 'alias', name='uq_state_alias')
    )
    op.create_table('control_total',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('raw_file_id', sa.Integer(), nullable=False),
    sa.Column('measure', sa.String(length=100), nullable=False),
    sa.Column('body_sum_rupees', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('footer_total_rupees', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('portal_value_crore', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('computed_value_crore', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('footer_match', sa.Boolean(), nullable=False),
    sa.Column('blueprint_match', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_file.id'], ),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_reject',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('raw_file_id', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('reason_code', sa.String(length=60), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_row',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('raw_file_id', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_file_id', 'row_no', name='uq_raw_row_file_rowno')
    )
    op.create_table('tenure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('tenure_label', sa.String(length=30), nullable=False),
    sa.Column('house', sa.String(length=2), nullable=False),
    sa.Column('constituency_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('source_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("house IN ('LS', 'RS')", name='ck_tenure_house'),
    sa.CheckConstraint("tenure_label IN ('18th Lok Sabha', 'Sitting MP')", name='ck_tenure_label'),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituency.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'tenure_label', name='uq_tenure_person_label')
    )
    op.create_table('work',
    sa.Column('work_key', sa.String(length=50), nullable=False),
    sa.Column('house', sa.String(length=2), nullable=False),
    sa.Column('house_source', sa.String(length=20), nullable=False),
    sa.Column('first_seen_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('first_seen_raw_file_id', sa.Integer(), nullable=False),
    sa.Column('raw_mp_name', sa.String(length=200), nullable=True),
    sa.Column('raw_activity_name', sa.Text(), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.Column('tenure_id', sa.Integer(), nullable=True),
    sa.Column('district_authority_id', sa.Integer(), nullable=True),
    sa.Column('activity_type_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("house IN ('LS', 'RS')", name='ck_work_house'),
    sa.CheckConstraint("house_source IN ('filename', 'house_column')", name='ck_work_house_source'),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_type.id'], ),
    sa.ForeignKeyConstraint(['district_authority_id'], ['district_authority.id'], ),
    sa.ForeignKeyConstraint(['first_seen_raw_file_id'], ['raw_file.id'], ),
    sa.ForeignKeyConstraint(['first_seen_snapshot_id'], ['source_snapshot.id'], ),
    sa.ForeignKeyConstraint(['tenure_id'], ['tenure.id'], ),
    sa.PrimaryKeyConstraint('work_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work')
    op.drop_table('tenure')
    op.drop_table('raw_row')
    op.drop_table('import_reject')
    op.drop_table('control_total')
    op.drop_table('state_alias')
    op.drop_table('raw_file')
    op.drop_table('person')
    op.drop_table('geo_name_crosswalk')
    op.drop_table('district_authority')
    op.drop_table('constituency')
    op.drop_table('state')
    op.drop_table('source_snapshot')
    op.drop_table('geo_area')
    op.drop_table('activity_type')
    # ### end Alembic commands ###
