# ruff: noqa: E501 -- report text and SQL read better unwrapped
"""
Phase 5a step 1 report: the House-qualified split of shared portal IDs, and
what it changed downstream. Compares the last analysis_run BEFORE the split
(--before) with the first run AFTER it (--after); both must have
risk_result rows. Writes docs/phase5a_identity_split_report.md.

    python scripts/report_identity_split.py --before 1 --after 2
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
from sqlalchemy import text  # noqa: E402

from app.db.session import get_session_factory  # noqa: E402
from app.ingest.normalize import normalize_name  # noqa: E402

REPORT_PATH = Path(
    os.environ.get("PHASE5A_REPORT_PATH")
    or Path(__file__).resolve().parents[2] / "docs" / "phase5a_identity_split_report.md"
)
TOL = 1e-9


def _modal_state(s: pd.Series):
    """Same rule as portfolio_concentration_signal's MP state (signals.py)."""
    m = s.mode()
    return m.iloc[0] if not m.empty else pd.NA


def q(conn, sql, **p) -> pd.DataFrame:
    return pd.read_sql(text(sql), conn, params=p)


def _table(df: pd.DataFrame) -> list[str]:
    cols = list(df.columns)
    out = ["| " + " | ".join(map(str, cols)) + " |", "| " + " | ".join("---" for _ in cols) + " |"]
    for row in df.itertuples(index=False):
        out.append("| " + " | ".join(
            f"{v:,}" if isinstance(v, (int, np.integer)) else str(v) for v in row) + " |")
    return out


def changed_keys(a: pd.DataFrame, b: pd.DataFrame, cols: list[str]) -> set[str]:
    """work_keys whose row differs between runs (present in both)."""
    both = a.index.intersection(b.index)
    a, b = a.loc[both, cols], b.loc[both, cols]
    diff = pd.Series(False, index=both)
    for c in cols:
        x, y = a[c], b[c]
        numeric = all(pd.api.types.is_numeric_dtype(v) and not pd.api.types.is_bool_dtype(v) for v in (x, y))
        if numeric:
            d = ~(((x - y).abs() <= TOL) | (x.isna() & y.isna()))
        else:
            d = ~((x.astype(str) == y.astype(str)) | (x.isna() & y.isna()))
        diff |= d
    return set(diff[diff].index)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--before", type=int, required=True)
    ap.add_argument("--after", type=int, required=True)
    args = ap.parse_args()
    r1, r2 = args.before, args.after
    Session = get_session_factory()
    L: list[str] = []
    with Session() as session:
        conn = session.connection()
        L += render(conn, r1, r2)
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"report written to {REPORT_PATH}")
    return 0


def render(conn, r1: int, r2: int) -> list[str]:
    L = ["# Phase 5a Step 1 -- splitting portal IDs shared across Houses", "",
         f"Compares analysis_run {r1} (before the split) with analysis_run {r2} (after). "
         "Generated by `backend_v2/scripts/report_identity_split.py`.", ""]

    # ---- 1. the split
    split = q(conn, "SELECT portal_id, ls_work_key, rs_work_key, evidence FROM work_identity_split ORDER BY portal_id::int")
    recs = q(conn, """
        SELECT w.work_key, w.portal_id, w.house, w.raw_mp_name, da.ida_name, at.label AS activity_type,
               ws.lifecycle_status, ws.recommended_date, ws.sanction_date, ws.actual_end_date,
               (SELECT COUNT(*) FROM payment p WHERE p.work_key = w.work_key) AS n_payments
        FROM work w
        LEFT JOIN district_authority da ON da.id = w.district_authority_id
        LEFT JOIN activity_type at ON at.id = w.activity_type_id
        LEFT JOIN work_state ws ON ws.work_key = w.work_key
          AND ws.source_snapshot_id = (SELECT id FROM source_snapshot WHERE code = 'snapshot_a')
        WHERE w.portal_id IN (SELECT portal_id FROM work_identity_split)""")
    ls, rs = recs[recs["house"] == "LS"].set_index("portal_id"), recs[recs["house"] == "RS"].set_index("portal_id")
    pairs = ls.join(rs, lsuffix="_ls", rsuffix="_rs", how="inner")
    total = q(conn, "SELECT house, COUNT(*) AS n FROM work GROUP BY house ORDER BY house")
    dup_identity = q(conn, "SELECT COUNT(*) AS n FROM (SELECT portal_id, house FROM work GROUP BY 1, 2 HAVING COUNT(*) > 1) x")
    L += ["## 1. The split", "",
          "BLUEPRINT §2 assumes the portal ID is unique across both Houses. For "
          f"{len(split)} IDs it is not: each is used by an LS recommended work and by a different RS "
          "sanctioned work. Phase 1/2 had stored each pair as one work, with the LS MP, district and "
          "description but the RS sanction, completion and payments. Each pair is now two works under "
          "the compound identity (portal_id, House). The LS half keeps work_key = portal ID; the RS half "
          "is keyed `<portal_id>-RS`. Nothing was re-ingested and no other Phase 1/2 logic changed "
          "(`app/ingest/p6_identity_split.py`, run by `scripts/run_identity_split.py` after "
          "`run_normalize.py`).", "",
          f"- Records now carrying a shared portal ID: **{len(recs)}** ({len(ls)} LS + {len(rs)} RS) from "
          f"{len(split)} IDs.",
          f"- (portal_id, House) pairs with more than one record: {int(dup_identity['n'].iloc[0])} "
          "(enforced by the unique constraint `uq_work_portal_id_house`).",
          "- Works in total: " + ", ".join(f"{h} {n:,}" for h, n in zip(total["house"], total["n"]))
          + f" = {int(total['n'].sum()):,} (was 128,883; +{len(rs)} RS records).",
          f"- Pairs whose MP differs: {int((pairs['raw_mp_name_ls'] != pairs['raw_mp_name_rs']).sum())}; "
          f"district authority differs: {int((pairs['ida_name_ls'] != pairs['ida_name_rs']).sum())}; "
          f"work type differs: {int((pairs['activity_type_ls'] != pairs['activity_type_rs']).sum())}.",
          "- LS halves' lifecycle: " + ", ".join(f"{k} {v}" for k, v in ls["lifecycle_status"].value_counts().items())
          + "; RS halves': " + ", ".join(f"{k} {v}" for k, v in rs["lifecycle_status"].value_counts().items()) + ".",
          f"- Payments: LS halves {int(ls['n_payments'].sum())}, RS halves {int(rs['n_payments'].sum())} "
          "(every payment row came from the RS expenditure file).",
          f"- LS attributes changed by re-deriving them from the LS recommended row alone: "
          f"{int(split['evidence'].map(lambda e: bool(e['ls_fields_changed'])).sum())} of {len(split)}. "
          "Phase 2 had already taken them from that row, since it is read first.",
          "", "First 10 pairs (all 136 are in `work_identity_split`):", ""]
    sample = pairs.head(10).reset_index()
    L += _table(pd.DataFrame({
        "portal_id": sample["portal_id"], "LS MP": sample["raw_mp_name_ls"], "LS district": sample["ida_name_ls"],
        "LS status": sample["lifecycle_status_ls"], "RS MP": sample["raw_mp_name_rs"],
        "RS district": sample["ida_name_rs"], "RS status": sample["lifecycle_status_rs"],
    }))
    scope = q(conn, "SELECT house, COUNT(*) AS n FROM work_context WHERE run_id = :r GROUP BY house ORDER BY house", r=r2)
    L += ["", "Scored population (sanctioned + completed) after the split: "
          + ", ".join(f"{h} {n:,}" for h, n in zip(scope["house"], scope["n"]))
          + ". These now equal the portal's own sanctioned-file row counts (LS 78,232 / RS 19,274, "
          "BLUEPRINT §2). Before the split they were LS 78,368 / RS 19,138.", ""]

    # ---- 2. compliance
    comp = q(conn, """SELECT run_id, check_code, rule, COUNT(*) AS evaluated,
                      COUNT(*) FILTER (WHERE NOT passed) AS failed
                      FROM compliance_result WHERE run_id IN (:a, :b) GROUP BY 1, 2, 3""", a=r1, b=r2)
    before = comp[comp["run_id"] == r1].set_index(["check_code", "rule"])
    after = comp[comp["run_id"] == r2].set_index(["check_code", "rule"])
    idx = before.index.union(after.index)
    ct = pd.DataFrame({
        "evaluated before": before["evaluated"].reindex(idx), "failed before": before["failed"].reindex(idx),
        "evaluated after": after["evaluated"].reindex(idx), "failed after": after["failed"].reindex(idx),
    }).reset_index()
    for c in ct.columns[2:]:
        ct[c] = ct[c].map(lambda v: "-" if pd.isna(v) else f"{int(v):,}")
    L += ["## 2. Compliance before and after", ""]
    L += _table(ct)
    c4 = after.loc[("C4", "dates_in_order"), "failed"]
    L += ["",
          f"- **C4 (dates in order): {int(before.loc[('C4', 'dates_in_order'), 'failed'])} -> {int(c4)}.** "
          "All the earlier violations were merged pairs, where an LS recommendation date (2025) sat "
          "against an unrelated RS sanction date (2023). After the split the LS half has only a "
          "recommendation date, so no ordering applies. The RS half has only sanction and completion "
          "dates, since RS has no recommended file in Snapshot A (Hard Limit 6). Those dates are in order."
          + (" C4 matches BLUEPRINT's baseline of 0." if int(c4) == 0 else " C4 does NOT reach 0; see above."),
          "- **C5** is unchanged. The RS halves keep the same sanction and completion dates the merged "
          "record had, and the LS halves were never sanctioned.",
          "- **C8 `sanctioned_in_recommended_file`:** the LS sanctioned population drops by the 136 LS "
          "halves, which are recommended-only now. It is 78,232, the LS sanctioned file's own count. The "
          "361 genuine gaps are unchanged.",
          "- **C8 identity rule:** in run 1 it counted raw sharing (`key_used_by_one_house`, 136 "
          "failures). From run 2 it checks that every (portal_id, House) has its own record "
          "(`one_record_per_portal_id_and_house`)."]

    flag2 = q(conn, """
        SELECT c.run_id, COUNT(*) AS rows,
               COUNT(*) FILTER (WHERE ws.lifecycle_status IN ('sanctioned', 'completed')) AS on_sanctioned_work,
               COUNT(*) FILTER (WHERE c.work_key IN (SELECT ls_work_key FROM work_identity_split)) AS on_split_ls
        FROM compliance_result c
        LEFT JOIN work_state ws ON ws.work_key = c.work_key
          AND ws.source_snapshot_id = (SELECT id FROM source_snapshot WHERE code = 'snapshot_a')
        WHERE c.run_id IN (:a, :b) AND c.check_code = 'C8' AND c.rule = 'flag2_has_stage_or_sanction'
          AND NOT c.passed GROUP BY 1 ORDER BY 1""", a=r1, b=r2)
    dq = q(conn, """
        SELECT run_id, config_name,
               COUNT(*) FILTER (WHERE confidence_components->'flags' ? 'flag_inconsistent') AS flag_inconsistent,
               COUNT(*) FILTER (WHERE confidence_components->'flags' ? 'cross_house_key_collision') AS collision,
               COUNT(*) FILTER (WHERE confidence_components->'flags' ? 'flag_inconsistent'
                                  AND confidence_components->'flags' ? 'cross_house_key_collision') AS both_flags
        FROM risk_result WHERE run_id IN (:a, :b) AND config_name = 'v4-candidate' GROUP BY 1, 2 ORDER BY 1""",
        a=r1, b=r2)
    fb, fa = flag2[flag2["run_id"] == r1].iloc[0], flag2[flag2["run_id"] == r2].iloc[0]
    db_, da_ = dq[dq["run_id"] == r1].iloc[0], dq[dq["run_id"] == r2].iloc[0]
    L += ["", "### FLAG-2 rows", "",
          f"- FLAG-2 rows in the LS recommended file: {int(fb['rows'])} before, **{int(fa['rows'])} after**. "
          "This counts file rows, so the split cannot change it. It still equals BLUEPRINT's 499.",
          f"- Of those rows, {int(fa['on_split_ls'])} belong to the LS halves of the split IDs. Rows "
          f"attached to a sanctioned or completed work: {int(fb['on_sanctioned_work'])} before, "
          f"**{int(fa['on_sanctioned_work'])} after**. Before the split, each of the 136 FLAG-2 rows "
          "(no stage, no sanction) was attached to a record that also carried an RS sanction, which "
          "made it look inconsistent. Now each sits on its own LS recommended-only work, which is what "
          "a FLAG-2 row describes.",
          f"- Double counting in confidence (scored works carrying both the inconsistent-FLAG and the "
          f"collision flag): {int(db_['both_flags'])} before, **{int(da_['both_flags'])} after**. "
          f"Inconsistent-FLAG flags on scored works: {int(db_['flag_inconsistent'])} -> "
          f"{int(da_['flag_inconsistent'])}; collision flags: {int(db_['collision'])} -> {int(da_['collision'])}.",
          ""]

    # ---- 3. recompute scope
    L += ["## 3. What the re-run changed", "",
          "The peer engine and signals compute leave-one-out statistics over whole groups, MP portfolios, "
          "authorities and weeks. A new append-only run therefore recomputes every work, and here it did. "
          "Recomputing everything is exact, not approximate. The table below checks the brief's intent: "
          "outputs change only for works connected to the 272 records, and every other work's result is "
          "identical to run 1.", ""]
    split_keys = set(split["ls_work_key"]) | set(split["rs_work_key"])
    attrs = q(conn, """
        SELECT w.work_key, w.raw_mp_name, w.district_authority_id, w.activity_type_id, da.state_id
        FROM work w LEFT JOIN district_authority da ON da.id = w.district_authority_id""").set_index("work_key")
    touched = attrs.loc[attrs.index.isin(split_keys)]
    link = pd.DataFrame({
        "mp": attrs["raw_mp_name"].isin(set(touched["raw_mp_name"].dropna())),
        "authority": attrs["district_authority_id"].isin(set(touched["district_authority_id"].dropna())),
        "state": attrs["state_id"].isin(set(touched["state_id"].dropna())),
        "type": attrs["activity_type_id"].isin(set(touched["activity_type_id"].dropna())),
    })
    connected = set(link.index[link.any(axis=1)]) | split_keys
    # portfolio_concentration compares an MP with peer MPs of the MP's MODAL
    # state (signals.py), so a multi-state MP's works in other states are
    # connected through it too.
    scoped = q(conn, """
        SELECT w.work_key, w.raw_mp_name, da.state_id FROM work_context wc
        JOIN work w ON w.work_key = wc.work_key
        LEFT JOIN district_authority da ON da.id = w.district_authority_id
        WHERE wc.run_id IN (:a, :b)""", a=r1, b=r2).drop_duplicates("work_key").set_index("work_key")
    scoped["mp"] = scoped["raw_mp_name"].map(normalize_name)
    modal = scoped.dropna(subset=["state_id"]).groupby("mp")["state_id"].agg(_modal_state)
    affected_states = set(touched["state_id"].dropna())
    via_modal = scoped.index[scoped["mp"].map(modal).isin(affected_states)]
    connected |= set(via_modal)

    ctx_cols = ["level", "group_key", "n_usable_excl_self", "distinct_other_mps", "peer_median", "peer_mad",
                "ref_group_key", "ref_median", "ref_mad"]
    ctx = {r: q(conn, f"SELECT work_key, {', '.join(ctx_cols)} FROM work_context WHERE run_id = :r", r=r)
           .set_index("work_key") for r in (r1, r2)}
    for r in ctx:
        for c in ("peer_median", "peer_mad", "ref_median", "ref_mad"):
            ctx[r][c] = pd.to_numeric(ctx[r][c])
    rows = []
    ch = changed_keys(ctx[r1], ctx[r2], ctx_cols)
    rows.append(("work_context (Phase 3)", ch, ctx[r1].index, ctx[r2].index))
    sig = {r: q(conn, "SELECT work_key, signal, eligible, score FROM signal_result WHERE run_id = :r", r=r)
           for r in (r1, r2)}
    nd_changed: set[str] = set()
    nd_delta = pd.Series(dtype=float)
    for s_ in sorted(sig[r1]["signal"].unique()):
        a = sig[r1][sig[r1]["signal"] == s_].set_index("work_key")
        b = sig[r2][sig[r2]["signal"] == s_].set_index("work_key")
        chs = changed_keys(a, b, ["eligible", "score"])
        if s_ == "near_duplicate":
            nd_changed = chs
            both = a.index.intersection(b.index)
            nd_delta = (a.loc[both, "score"] - b.loc[both, "score"]).abs()
        rows.append((f"signal_result: {s_} (Phase 4)", chs, a.index, b.index))
    risk = {r: q(conn, "SELECT work_key, config_name, risk, tier, confidence FROM risk_result WHERE run_id = :r", r=r)
            for r in (r1, r2)}
    for c in ("v3-compatible", "v4-candidate"):
        a = risk[r1][risk[r1]["config_name"] == c].set_index("work_key")
        b = risk[r2][risk[r2]["config_name"] == c].set_index("work_key")
        rows.append((f"risk_result: {c} (Phase 5)", changed_keys(a, b, ["risk", "tier", "confidence"]),
                     a.index, b.index))
    tab = []
    unexplained = 0
    for name, chs, ia, ib in rows:
        outside = chs - connected
        # near_duplicate is national by design (TF-IDF vocabulary and IDF are
        # fitted on every description), and risk inherits it.
        if "near_duplicate" in name:
            residual = set()
        elif name.startswith("risk_result"):
            residual = outside - nd_changed
        else:
            residual = outside
        unexplained += len(residual)
        tab.append({"output": name, "works in both runs": len(ia.intersection(ib)), "changed": len(chs),
                    "changed outside connected set": len(outside), "unexplained": len(residual),
                    "only in before": len(ia.difference(ib)), "only in after": len(ib.difference(ia))})
    L += _table(pd.DataFrame(tab))
    L += ["",
          f"\"Connected\" means one of the 272 split records, or a work sharing an MP, district authority, "
          f"state or work type with one of them: {len(connected):,} works. Those are the populations the "
          "peer groups, portfolio shares, authority shares, cadences and near-duplicate blocks are "
          "computed over. \"Only in before/after\" are the 136 LS halves, which left the scored "
          "population as recommended-only works, and the 136 RS halves, which entered it.", ""]
    nd_out = nd_delta.reindex(sorted(nd_changed - connected))
    L += ["- **near_duplicate is national by design.** Its TF-IDF vocabulary and phrase-frequency "
          "weights are fitted over every description (BLUEPRINT §6 \"national phrase-frequency "
          "discount\"). Removing 136 descriptions from scope and adding 136 others therefore nudges every "
          f"vector. On works outside the connected set the median change is {nd_out.median():.1e}, "
          f"{int((nd_out > 0.01).sum())} move by more than 0.01, and the largest move is "
          f"{nd_out.max():.3f}. Every risk change outside the connected set comes from this signal.",
          "- " + ("Every other change is on a connected work: **0 unexplained**." if unexplained == 0 else
                  f"**{unexplained} changes are unexplained.** Investigate before trusting the re-run."), ""]
    rd = q(conn, """SELECT a.config_name, COUNT(*) FILTER (WHERE a.tier <> b.tier) AS tier_changes,
        COUNT(*) FILTER (WHERE ABS(a.risk - b.risk) > 1) AS risk_moved_over_1pt
        FROM risk_result a JOIN risk_result b ON b.work_key = a.work_key AND b.config_name = a.config_name
        AND b.run_id = :b WHERE a.run_id = :a GROUP BY 1 ORDER BY 1""", a=r1, b=r2)
    L += ["Works present in both runs whose risk moved by more than 1 point, or whose tier changed:", ""]
    L += _table(rd)
    L += [""]

    # ---- 4. tiers
    t = q(conn, "SELECT run_id, config_name, tier, COUNT(*) AS n FROM risk_result WHERE run_id IN (:a, :b) "
          "GROUP BY 1, 2, 3", a=r1, b=r2)
    piv = t.pivot_table(index=["config_name", "tier"], columns="run_id", values="n", fill_value=0,
                        aggfunc="sum").astype(int, errors="ignore").reset_index()
    piv.columns = ["config", "tier", f"run {r1}", f"run {r2}"]
    L += ["## 4. Tier counts before and after (fusion formula, tiers and corroboration unchanged)", ""]
    L += _table(piv)
    split_tiers = q(conn, """SELECT config_name, tier, COUNT(*) AS n FROM risk_result
        WHERE run_id = :r AND work_key IN (SELECT rs_work_key FROM work_identity_split) GROUP BY 1, 2 ORDER BY 1, 2""",
                    r=r2)
    L += ["", "The 136 RS halves, scored for the first time as themselves:", ""]
    L += _table(split_tiers)
    L += ["", "The committed Phase 5 gate report (`docs/phase5_gate_report.md`) still describes run "
          f"{r1}. It was not regenerated in this step. The same gate analysis for run {r2} can be "
          "produced with `scripts/run_risk.py --report-only` when you want it.", ""]
    return L


if __name__ == "__main__":
    raise SystemExit(main())
