# ruff: noqa: E501 -- report text reads better unwrapped
"""
Phase 6/8 CLI: BLUEPRINT.md §7 B4 multivariate atypicality (evidence only)
on one run, then docs/phase6_atypicality_report.md. Run after run_risk.py
(and publish_run.py).

    python scripts/run_atypicality.py              # the published run, else latest risk run
    python scripts/run_atypicality.py --run 3
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
from scipy.stats import pearsonr, spearmanr  # noqa: E402
from sklearn.covariance import MinCovDet  # noqa: E402
from sqlalchemy import func, select, text  # noqa: E402

from app.analytics import atypicality, atypicality_run, fusion, publish  # noqa: E402
from app.db.session import get_session_factory  # noqa: E402
from app.models.analytics import RiskResult  # noqa: E402

REPORT_PATH = Path(
    os.environ.get("PHASE6_REPORT_PATH")
    or Path(__file__).resolve().parents[2] / "docs" / "phase6_atypicality_report.md"
)
TOP = 1000
# First Phase 6 run (run 1, before the owner's fix), Mahalanobis on all seven
# features incl. distinct_payee_count: the numbers the fix is compared against.
BEFORE_FIX = {("robust_mahalanobis", "Spearman"): 0.293, ("robust_mahalanobis", "Pearson"): 0.266,
              ("isolation_forest", "Spearman"): 0.288, ("isolation_forest", "Pearson"): 0.279}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", type=int, default=None)
    ap.add_argument("--replace", action="store_true",
                    help="delete this run's atypicality rows, facts and model_version entries first")
    args = ap.parse_args()
    with get_session_factory()() as session:
        run_id = args.run
        pub = publish.published(session)
        if run_id is None:
            run_id = pub.run_id if pub else session.execute(select(func.max(RiskResult.run_id))).scalar()
        data = atypicality_run.run(session, run_id, replace=args.replace)
        session.commit()
        sig = pd.read_sql(text("SELECT work_key, signal, score FROM signal_result WHERE run_id = :r AND eligible"),
                          session.connection(), params={"r": run_id})
        report = render(run_id, data, sig, publish.published(session))
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"atypicality written for run {run_id}; report at {REPORT_PATH}")
    return 0


def _table(df: pd.DataFrame) -> list[str]:
    cols = list(df.columns)
    out = ["| " + " | ".join(map(str, cols)) + " |", "| " + " | ".join("---" for _ in cols) + " |"]
    for row in df.itertuples(index=False):
        out.append("| " + " | ".join(
            f"{v:,}" if isinstance(v, (int, np.integer)) else (f"{v:.3f}" if isinstance(v, float) else str(v))
            for v in row) + " |")
    return out


def _corr(a: pd.Series, b: pd.Series) -> tuple[int, float, float]:
    m = a.notna() & b.notna()
    if m.sum() < 3:
        return int(m.sum()), float("nan"), float("nan")
    return int(m.sum()), float(spearmanr(a[m], b[m]).statistic), float(pearsonr(a[m], b[m]).statistic)


def _top(s: pd.Series, n: int = TOP) -> pd.Index:
    return s.dropna().sort_values(ascending=False, kind="mergesort").index[:n]


def render(run_id: int, d: dict, sig: pd.DataFrame, pub) -> list[str] | str:
    X, raw, fitted = d["X"], d["raw"], d["fitted"]
    house = raw["house"]
    maha = fitted["robust_mahalanobis"]["frame"]
    iso = fitted["isolation_forest"]["frame"]
    L = ["# Phase 6/8 -- Multivariate atypicality (BLUEPRINT §7 B4), evidence only", "",
         f"analysis_run {run_id} (snapshot as of {d['as_of'].date()}). Generated by "
         "`backend_v2/scripts/run_atypicality.py`.", ""]

    L += ["## Default risk configuration", ""]
    if pub:
        L += [f"`published_run` points at run {pub.run_id} with default config **{pub.default_config_name}** "
              f"(config hash `{pub.default_config_hash}`), per {pub.decision_ref}. Both configurations are still "
              "computed and stored in risk_result; this pointer records which one is the default.", ""]
    else:
        L += ["No published_run pointer is set.", ""]

    L += ["## What this layer is", "",
          "Evidence only. Results live in `atypicality_result`, separate from `signal_result`. Phase 5 fusion "
          "reads only the six base signals, so these scores never enter risk, the active-signal count or "
          "corroboration (gate G6). Tests check this directly: they insert the scores next to the six signals "
          "and confirm fusion output is unchanged, and they confirm signal_result rejects them.",
          "",
          "Features, per work: " + ", ".join(f"`{f}`" for f in atypicality.FEATURES) + ". Amount, peer ratio, "
          "days, counts and description length are log- or log1p-transformed. The peer ratio is Phase 3's own "
          "peer median, fed in, not re-derived. MP identity, payee identity and risk score are blocked in code: "
          "`assert_no_leakage` raises `LeakageError` on any such column, on every fit and score.",
          "",
          "- **Robust Mahalanobis** (primary): sklearn MinCovDet, seed "
          f"{atypicality.SEED}, on six features: all except `distinct_payee_count` (owner's decision, see "
          "below). Stores the distance and each feature's contribution; the contributions sum to the squared "
          "distance.",
          "- **Isolation Forest** (comparator): 200 trees, seed "
          f"{atypicality.SEED}, contamination left at `auto`. Contamination only sets predict()'s inlier/outlier "
          "label. That label is never used or stored, so no \"flagged %\" exists to tune; only the continuous "
          "score is kept.",
          "- Both are registered in `model_version`: algorithm, feature-spec hash "
          f"`{atypicality.feature_spec_hash()[:16]}...`, training snapshot, seed, params, metrics and "
          "artifact hash.", ""]

    L += ["## Coverage (missing feature = not evaluated, never 0)", ""]
    miss = pd.Series([f for fs in maha["missing_features"] for f in fs]).value_counts()
    rows = []
    for h in ("LS", "RS"):
        m = house == h
        rows.append({"house": h, "works": int(m.sum()), "evaluated": int(maha.loc[m, "eligible"].sum()),
                     "not evaluated": int((~maha.loc[m, "eligible"]).sum())})
    L += _table(pd.DataFrame(rows))
    L += ["", "Works missing each feature: " + ", ".join(f"{k} {v:,}" for k, v in miss.items()), "",
          "**No Rajya Sabha work is evaluated.** Every RS work lacks a recommendation date, because the RS "
          "recommended file is absent from Snapshot A (BLUEPRINT §2 Hard Limit 6). Per the missing-data rule "
          "they are not evaluated rather than imputed. So RS-side orthogonality cannot be computed either.", ""]

    L += ["## Orthogonality to cost anomaly (report only, not pass/fail)", "",
          "Correlation between this layer's scores and Phase 4's cost_anomaly score, over works evaluated by "
          "both. BLUEPRINT §7 warns a multivariate model would mostly rediscover large amounts. A value near 1 "
          "would mean it is doing exactly that.", ""]
    cost = sig[sig["signal"] == "cost_anomaly"].set_index("work_key")["score"]
    rows = []
    for method, fr in (("robust_mahalanobis", maha), ("isolation_forest", iso)):
        for h in ("LS", "RS", "both"):
            m = (house == h) if h != "both" else pd.Series(True, index=house.index)
            n, rho, r = _corr(fr.loc[m, "score"], cost.reindex(fr.index)[m])
            rows.append({"method": method, "house": h, "n": n, "Spearman": rho, "Pearson": r})
    L += _table(pd.DataFrame(rows))
    both = {(r_["method"], k): r_[k] for r_ in rows if r_["house"] == "both" for k in ("Spearman", "Pearson")}
    L += ["", "Before vs after the Mahalanobis fix (both Houses; RS contributes no works):", ""]
    L += _table(pd.DataFrame([{"method": m_, "measure": k, "before fix": BEFORE_FIX[(m_, k)],
                               "after fix": both[(m_, k)], "change": both[(m_, k)] - BEFORE_FIX[(m_, k)]}
                              for (m_, k) in BEFORE_FIX]))
    L += ["", "Context: Spearman correlation with every base signal and with the amount itself (both Houses):", ""]
    rows = []
    for method, fr in (("robust_mahalanobis", maha), ("isolation_forest", iso)):
        row = {"method": method}
        for s in fusion.BASE_SIGNALS:
            row[s] = _corr(fr["score"], sig[sig["signal"] == s].set_index("work_key")["score"]
                           .reindex(fr.index))[1]
        row["log_amount"] = _corr(fr["score"], X["log_amount"])[1]
        rows.append(row)
    L += _table(pd.DataFrame(rows))
    n, rho, _ = _corr(maha["score"], iso["score"])
    L += ["", f"Agreement between the two methods: Spearman {rho:.3f} over {n:,} works; top-{TOP} overlap "
          f"{len(_top(maha['score']).intersection(_top(iso['score']))) / TOP:.1%}.", ""]

    L += ["## What drives the robust distance", "",
          f"Mean share of the squared distance contributed by each feature, among the top {TOP} works by "
          "robust distance and among all evaluated works:", ""]
    el = maha.index[maha["eligible"]]
    C = pd.DataFrame(list(maha.loc[el, "contributions"]), index=el)[list(atypicality.MAHALANOBIS_FEATURES)]
    share = C.div(C.sum(axis=1), axis=0)
    top = _top(maha["score"])
    L += _table(pd.DataFrame({"feature": atypicality.MAHALANOBIS_FEATURES,
                              f"top {TOP}": share.loc[top].mean().to_numpy(),
                              "all evaluated": share.mean().to_numpy()}))
    met = fitted["robust_mahalanobis"]["metrics"]
    L += ["", f"MCD support: {met['support_size']:,} of {met['n_evaluated']:,} works. Covariance condition "
          f"number: {met['covariance_condition_number']:.1f} (eigenvalues "
          + ", ".join(f"{e:.4f}" for e in met["covariance_eigenvalues"]) + ").", ""]

    L += ["## Ablation (BLUEPRINT §7 B4 validation)", "",
          "The robust distance was refit without each feature in turn, same seed. Low rank agreement or low "
          "top-1000 overlap means the ranking leans on that feature.", ""]
    Xe = X.loc[maha["eligible"], list(atypicality.MAHALANOBIS_FEATURES)]
    base = maha.loc[Xe.index, "score"]
    rows = []
    for f in atypicality.MAHALANOBIS_FEATURES:
        sub = Xe.drop(columns=f).to_numpy(float)
        m = MinCovDet(**atypicality.MCD_PARAMS).fit(sub)
        dist = pd.Series(np.sqrt(np.clip(m.mahalanobis(sub), 0, None)), index=Xe.index)
        rows.append({"feature removed": f, "Spearman vs full": float(spearmanr(base, dist).statistic),
                     f"top-{TOP} overlap": f"{len(_top(base).intersection(_top(dist))) / TOP:.1%}"})
    L += _table(pd.DataFrame(rows))

    facts = d["facts"]
    ev_keys = maha.index[maha["eligible"]]
    L += ["", "## Evidence fact: pays the same payee more than once", "",
          "Why `distinct_payee_count` is not in the Mahalanobis feature set (owner's decision): in the "
          "MCD's robust core every work has exactly as many payments as distinct payees. With both counts "
          "in, the covariance was singular (condition number about 2e16), and a work paying one payee "
          "repeatedly got essentially zero weight in the distance. The robust distance now uses the other "
          "six features. Isolation Forest keeps all seven. The repeat-payment pattern is recorded as a plain "
          "fact in `work_evidence_fact` (`pays_same_payee_more_than_once`): no score, never read by fusion, "
          "the active-signal count or corroboration.", "",
          f"- Scored works with the fact: **{len(facts):,}** (LS {int((facts['house'] == 'LS').sum()):,}, "
          f"RS {int((facts['house'] == 'RS').sum()):,}).",
          f"- Of those, evaluated by the Mahalanobis layer: {int(facts['work_key'].isin(ev_keys).sum()):,}. "
          "These are the works the singular fit had been blind to.",
          "- Detail stored per work: payment rows, distinct payees, and the most payments to any one payee.",
          f"- MCD covariance after the fix: condition number {met['covariance_condition_number']:.1f}.", ""]
    L += ["## Limitations", "",
          "- RS works are unscored because the RS recommended file (Hard Limit 6) doesn't supply a "
          "recommendation date, consistent with the existing missing-data policy.",
          "- No labelled outcomes. This layer is evidence for reviewers; whether it is useful is BLUEPRINT "
          "§7's reviewer-usefulness check, not shown here. Entry into the risk score needs gate G6.", ""]
    L += ["## Guarantees checked", "",
          f"- risk_result for run {run_id}: md5 `{d['risk_md5']}` before and after this step, identical (the "
          "step aborts otherwise). It is also recorded in each model_version's metrics.",
          "- Same input and seed give identical scores for both methods (test).",
          "- Injecting MP identity, payee identity or a risk score into the matrix raises LeakageError (test).",
          "- A missing feature gives not evaluated with a NULL score, never 0 (test, and a database CHECK).",
          "- These scores and facts do not change fusion output, and signal_result's CHECK rejects them "
          "(tests).", ""]
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    raise SystemExit(main())
